### ISSUE TITLE
add sounds

### ISSUE THREAD

**Issue by Deathlymad** [MDeiml/LD48#55]

**Comment by MDeiml** [comment]
Added breath sounds

**Comment by Deathlymad** [comment]
Particularly needed for monsters

**Comment by Deathlymad** [comment]
- [x] Collect Oxygen
- [x] Octopus
- [x] Shark
- [x] music
- [x] add hurt
- [x] collecting dead guy
- [ ] anglerfish
- [x] breaking surface
- [x] ambience
- [x] idle sound?

**Comment by MDeiml** [comment]
Is collect oxygen really done? I think we wanted to change to the "single pop" sound and we need a "hydraulic" noise
